### ISSUE TITLE
errors in main.sh?

### ISSUE THREAD

**Issue by RulyTafzil** [fabianehmel/haacker#3]
When running t/process-etopo1-data/main.sh I get the following error message: 

> haaker@1.0.1 process-etopo1-data /mnt/z/repos/haacker
> sh process-etopo1-data/main.sh

process-etopo1-data/main.sh: 62: process-etopo1-data/main.sh: [[: not found
process-etopo1-data/main.sh: 82: process-etopo1-data/main.sh: Syntax error: "(" unexpected (expecting "}")

**Comment by fabianehmel** [comment]
Hi there.

Thank you for having a look into this project!
I could not reproduce your issue, but identified the probable cause of it. I just pushed an update, please check if it works for you now. If you still experience the issue, please let me know on which OS you are working—thanks!

**Comment by RulyTafzil** [comment]
Thank you for the quick response!
Your question about OS got me thinking. I'm on windows 10, running the script in Ubuntu 18.04 in a VM. I think the issue is that Ubuntu is defaulting to dash to run the script? 

When I manually run main.sh using bash it works! 

I love the project and thank you so much for making it open source!

**Comment by fabianehmel** [comment]
Yes, the issue was indeed that I used bash-specific commands in the script. That lead to an error when running it using sh. Those specific commands are now replaced—it should be possible to run the script with a standard shell.
